# Generated by Django 5.0.2 on 2024-02-29 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_noticias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticias',
            options={'ordering': ['title'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
    ]
