# Generated by Django 5.0.2 on 2024-02-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_noticias_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('resume', models.TextField()),
                ('text', models.TextField()),
                ('authors', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('keywords', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['title'],
            },
        ),
    ]
