# Generated by Django 5.0.2 on 2024-02-29 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_noticias2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticias2',
            options={'ordering': ['title'], 'verbose_name': 'Noticia2', 'verbose_name_plural': 'Noticias2'},
        ),
    ]
