# Generated by Django 5.0.2 on 2024-02-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_noticias2_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('author', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('urlToImage', models.TextField()),
                ('publishedAt', models.TextField()),
                ('content', models.TextField()),
                ('text', models.TextField()),
                ('topImage', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
                ('resume', models.TextField()),
            ],
            options={
                'verbose_name': 'Factify',
                'verbose_name_plural': 'Factifys',
                'ordering': ['title'],
            },
        ),
    ]
