# Generated by Django 5.0.2 on 2024-02-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_factify'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Factify',
            new_name='Factifys',
        ),
    ]
