# Generated by Django 5.0.2 on 2024-02-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_factify_factifys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factifys',
            old_name='topImage',
            new_name='top_image',
        ),
        migrations.RemoveField(
            model_name='factifys',
            name='image',
        ),
    ]
