# Generated by Django 5.0.2 on 2024-02-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_topimage_factifys_top_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factifys',
            old_name='top_image',
            new_name='topImage',
        ),
    ]
