# Generated by Django 5.0.2 on 2024-02-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_top_image_factifys_topimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factifys',
            old_name='topImage',
            new_name='top_image',
        ),
    ]
